export { default as userChart } from './chart/userChart.svg'
export { default as sessionChart } from './chart/sessionChart.svg'

export { default as USicon } from './countries/USUS.svg'
export { default as AUicon } from './countries/AU.svg'
export { default as CAicon } from './countries/CA.svg'
export { default as GBicon } from './countries/GB.svg'
export { default as INicon } from './countries/IN.svg'
export { default as PlusPurpleIcon } from './icons/plusPurpleIcon.svg'
export { default as purpleNote } from './icons/purpleNote.svg'
export { default as ggIcon } from './icons/Google.svg'
export { default as microIcon } from './icons/Microsoft.svg'
